### PR TITLE
299: Dechunk and fix probes e2e tests

### LINKED ISSUE #80: UI tests: Add validation of successful object creation in the UI
We need to add validation that objects have correct properties. 
For example, after group label has been created we need to make sure that group, rank and condition are exactly the same as we specified in the input. Currently tests only validate label name by deleting label from the page.

In addition to that, `checkGroupLabelNotExist(groupName)` is not doing the right thing. Fix it at the same time when validation is added.

### PR DESCRIPTION
**Pull request by susannahmarcus**
- dechunks the probes tests into smaller segments
- takes some of the labels utils/constants and moves them to the support file since they work in other scopes (when having to do with the listing pages, headers, and buttons)
- Adds ability to verify field values on the probes form (labels form already addressed by #328)
- Adds update tests to probes

closes #80

### CODE REVIEW

File: cypress/e2e/Labels/utilsAndConstants/labelsFormUtils.ts [hunk 1]
```diff
@@ -14,3 +14,70 @@ export const checkPresenceOfGroupNameInput = (options: {
...
+    groupName !== UNGROUPED &&
+    cy.get('input[aria-label="Group Name"]').clear().type(groupName);
+
+  rank &&
+    cy.get('input[aria-label="Group Rank"]').clear().type(rank).type("{enter}");
+
+  cy.get('textarea[aria-label="Condition"]')
+    .clear()
+    .type(condition)
+    .type("{command+enter}");
```
Comment (doronrosenberg) [inline cypress/e2e/Labels/utilsAndConstants/labelsFormUtils.ts:38]: will this work on non-mac?

File: cypress/e2e/Labels/utilsAndConstants/labelsFormUtils.ts [hunk 2]
```diff
@@ -14,3 +14,70 @@ export const checkPresenceOfGroupNameInput = (options: {
...
+      .clear()
+      .type(newRank)
+      .type("{enter}");
+
+  newCondition &&
+    cy
+      .get('textarea[aria-label="Condition"]')
+      .clear()
+      .type(newCondition)
+      .type("{command+enter}");
```
Comment (doronrosenberg) [inline cypress/e2e/Labels/utilsAndConstants/labelsFormUtils.ts:67]: ditto

File: cypress/e2e/Labels/utilsAndConstants/labelsFormUtils.ts (hunk 1 above)
Comment (vqmarkman) [reply cypress/e2e/Labels/utilsAndConstants/labelsFormUtils.ts:38]: @doronrosenberg , if you are referring to `command+enter` then yes, it works on mac and in GHA.
This was the fix for https://github.com/sundeck-io/OpsCenter/issues/39 (all the details on implementation are there)

File: cypress/e2e/Labels/utilsAndConstants/labelsUtils.ts [hunk 3]
```diff
@@ -180,28 +137,19 @@ export function checkUpdatedLabelExists(options: {
...
-            .contains(condition)
-            .should("exist");
+          cy.dataId("stVerticalBlock").contains(condition).should("exist");
 
-        rank &&
-          cy
-            .dataId({ value: "stVerticalBlock" })
-            .contains(rank)
-            .should("exist");
+        rank && cy.dataId("stVerticalBlock").contains(rank).should("exist");
```
Comment (vqmarkman) [inline cypress/e2e/Labels/utilsAndConstants/labelsUtils.ts:149]: @susannahmarcus , I don't understand what happened with formatting (and there are bunch of other cases like this).  Code in lines 195 - 199 is new since yesterday. 
Did you manually remove `{ value:` part and then because line became shorter it got collapsed into a single line? 
If you did not manually remove it, it's almost like another version `prettier` is doing it...

File: cypress/support/customCypressUtils.ts [hunk 4]
```diff
@@ -7,32 +7,27 @@ declare global {
...
        */
-      dataCy(options: {
-        value: string;
-        timeout?: number;
-      }): Chainable<JQuery<HTMLElement>>;
-      dataId(options: {
-        value: string;
-        timeout?: number;
-      }): Chainable<JQuery<HTMLElement>>;
+      dataCy(value: string, timeout?: number): Chainable<JQuery<HTMLElement>>;
```
Comment (vqmarkman) [inline cypress/support/customCypressUtils.ts:10]: another case: 
`options: {` <--- removed and reformatted
        value: string;
        timeout?: number;
})

**Review by vqmarkman — APPROVED** [review]
Awesome, ship it!

File: cypress/e2e/Labels/utilsAndConstants/labelsUtils.ts (hunk 3 above)
Comment (susannahmarcus) [reply cypress/e2e/Labels/utilsAndConstants/labelsUtils.ts:149]: formatting:
in JS, if you're looking to see if something exists, you can just have the check structured like this. It basically says `if rank is defined, do this`.
As for the `{ value: "stVerticalBlock" }` turning into `"stVerticalBlock" ` it's for the custom utils I've added. I changed their arguments structure because I made it an object before since there was a optional timeout increase, but noticed that nothing was using it and it was adding the step of typing `{value:}` for nothing.

File: cypress/support/customCypressUtils.ts (hunk 4 above)
Comment (susannahmarcus) [reply cypress/support/customCypressUtils.ts:10]: Yeah, I did this manually, as specified in the last comment

**Review by doronrosenberg — APPROVED** [review]

File: package.json [hunk 5]
```diff
@@ -1,6 +1,6 @@
 {
   "devDependencies": {
-    "cypress": "^12.16.0",
+    "cypress": "^13.2.0",
```
Comment (vqmarkman) [inline package.json:3]: @susannahmarcus , you might want to enable videos again. In this version they are turned off by default. Only screenshots are recorded.

```video: true```

Comment (vqmarkman) [reply package.json:3]: never mind, I see it.

**Review by vqmarkman — APPROVED** [review]
