### PR TITLE
fix grants in migration script

### LINKED ISSUE #100: Remove use of `*` in projections
We currently use `*` in projections for the enriched query data. We need to remove this to ensure all tables/views are well defined and to allow us to make improvements/changes to the underlying tables without breaking intermediate stages

### PR DESCRIPTION
**Pull request by rymurr**
We need to keep the grants across re-creation of the tables/views

closes #100

### CODE REVIEW

File: bootstrap/016_query_history.sql [hunk 1]
```diff
@@ -74,8 +76,22 @@ AS
...
+                tools.qtag_to_map(qtag) as qtag_filter,
+        unloaded_direct_compute_credits * INTERNAL.GET_CREDIT_COST(warehouse_id) as COST, * exclude (period_plus, record_type) from internal_reporting_mv.query_history_complete_and_daily where RECORD_TYPE = 'DAILY'
+=======
+    create or replace view reporting.enriched_query_history_daily
+    COPY GRANTS
+    as
+        select
+                tools.qtag_to_map(qtag) as qtag_filter,
+        unloaded_direct_compute_credits * INTERNAL.GET_CREDIT_COST(warehouse_id) as COST, * exclude (period_plus, record_type) from internal_reporting_mv.query_history_complete_and_daily where RECORD_TYPE = 'DAILY'
+>>>>>>> Stashed changes:bootstrap/017_query_history.sql
```
Comment (joshelser) [inline bootstrap/016_query_history.sql:94]: whoops

Comment (rymurr) [reply bootstrap/016_query_history.sql]: indeed. fixed

**Comment by rymurr** [comment]
merging to set up a deploy. shout if you have any issues

**Comment by jinfengni** [comment]
Looks good to me.

**Review by joshelser — COMMENTED** [review]
👍🏼
